resolver: lts-17.12

packages:
- '.'

#extra-deps:
#- llvm-hs-9.0.1.1
#- llvm-hs-pure-9.0.1.1

extra-deps:
- git: git@github.com:llvm-hs/llvm-hs.git
  commit: fb31d039066fb0e5f7d8a41110bb589733e0263d
  subdirs:
  - llvm-hs
  - llvm-hs-pure

flags:
  llvm-hs:
    shared-llvm: true

ghc-options:
  llvm-hs: -optcxx=-std=c++11 -optcxx=-lstdc++ -optcxx=-fno-rtti -optcxx=-Wno-init-list-lifetime -optcxx=-Wno-stringop-overflow
  "$targets": -Wall

rebuild-ghc-options: true
