resolver: lts-17.12

packages:
- '.'

#extra-deps:
#- llvm-hs-9.0.1.1
#- llvm-hs-pure-9.0.1.1

extra-deps:
- git: git@github.com:llvm-hs/llvm-hs.git
  commit: f9fbb35fc6c393e311c2d50935130b6202c17270
  subdirs:
  - llvm-hs
  - llvm-hs-pure

flags:
  llvm-hs:
    shared-llvm: true

ghc-options:
  llvm-hs: -optcxx=-std=c++11 -optcxx=-lstdc++ -optcxx=-fno-rtti -optcxx=-Wno-init-list-lifetime -optcxx=-Wno-stringop-overflow
